title: khzher
email: hwaizher@gmail.com
description: Khzher website
url: "https://khzher.org"
twitter: 

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed