title: Write, and Write Nots
email: hwaizher@gmail.com
description: Write and Write Nots
url: "https://khzher.org"
twitter: 

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed